### ISSUE TITLE
RoR Recipe App Group Project Kanban Board Set-up 

### ISSUE THREAD

**Issue by bill7pearl** [bill7pearl/recipe-rails#12]
### Hello theeeere 😄 
There are three people in this group:
@Salwa99 
@bill7pearl 
@SabiMantock 
#### cheers 🥂

**Comment by Qoosim** [comment]
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
-  Kanban board set up properly. :heavy_check_mark: 
-  Tasks distributed fairly. :heavy_check_mark: 

![](https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
